INSERT OR IGNORE INTO learning_areas (id, code, name, icon, sort_order, is_active, created_at, updated_at) VALUES
('thai','THAI','ภาษาไทย','book-open',1,1,datetime('now'),datetime('now')),
('math','MATH','คณิตศาสตร์','calculator',2,1,datetime('now'),datetime('now')),
('science','SCI','วิทยาศาสตร์และเทคโนโลยี','flask',3,1,datetime('now'),datetime('now')),
('social','SOC','สังคมศึกษา ศาสนา และวัฒนธรรม','landmark',4,1,datetime('now'),datetime('now')),
('health','HEALTH','สุขศึกษาและพลศึกษา','heart-pulse',5,1,datetime('now'),datetime('now')),
('arts','ART','ศิลปะ','palette',6,1,datetime('now'),datetime('now')),
('career','CAREER','การงานอาชีพ','briefcase',7,1,datetime('now'),datetime('now')),
('languages','LANG','ภาษาต่างประเทศ','language',8,1,datetime('now'),datetime('now')),
('guidance','GUIDANCE','กิจกรรมพัฒนาผู้เรียน','people-group',9,1,datetime('now'),datetime('now')),
('management','MANAGEMENT','ฝ่ายบริหาร','user-tie',10,1,datetime('now'),datetime('now'));
INSERT OR IGNORE INTO system_settings (key,value,updated_at) VALUES
('system_name','ระบบลงทะเบียนรับ iPad สำหรับครูและนักเรียนโรงเรียนจอมทอง',datetime('now')),
('project_name','โครงการส่งเสริมการเรียนรู้ขั้นพื้นฐานทุกที่ ทุกเวลา (Anywhere Anytime) สำหรับโรงเรียน',datetime('now')),
('school_name','โรงเรียนจอมทอง',datetime('now')),('subdistrict','ข่วงเปา',datetime('now')),('district','จอมทอง',datetime('now')),
('province','เชียงใหม่',datetime('now')),('organization','สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาเชียงใหม่',datetime('now')),
('device_brand','Apple',datetime('now')),('device_model','iPad A16 WiFi+Cellular 128GB',datetime('now')),
('approver_name','',datetime('now')),
('teacher_approver_name','',datetime('now')),
('student_approver_name','',datetime('now')),('survey_status','OPEN',datetime('now')),
('hero_eyebrow','Anywhere Anytime',datetime('now')),('hero_title','ลงทะเบียนรับ',datetime('now')),
('hero_product_name','iPad',datetime('now')),('hero_product_suffix','ยืมเรียน',datetime('now')),
('hero_free_label','ฟรี!!!',datetime('now')),('hero_audience','สำหรับครูและนักเรียนโรงเรียนจอมทอง',datetime('now')),
('teacher_survey_status','OPEN',datetime('now')),('student_survey_status','OPEN',datetime('now')),
('announcement','โปรดเลือกกลุ่มสาระการเรียนรู้และชื่อของท่านเพื่อบันทึกความประสงค์',datetime('now')),('survey_end_date','',datetime('now'));
