"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBan, faCheck, faChevronLeft, faChevronRight, faCircleCheck, faClock,
  faHistory, faMagnifyingGlass, faRotateLeft, faSchool, faSpinner,
  faTabletScreenButton, faUserTie, faUsers, faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { toast } from "sonner";
import { readJson } from "@/lib/client-json";

type Row=Record<string,unknown>;
type Tab="QUICK"|"LIST"|"HISTORY";
type Summary={total:number;ready:number;received:number;returned:number};
type Area={id:string;name:string};
const PAGE_SIZE=50;
const text=(value:unknown)=>value==null?"":String(value);

function formatDateTime(value:unknown){const raw=text(value);if(!raw)return"—";const date=new Date(raw);if(Number.isNaN(date.getTime()))return raw;return date.toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Bangkok"});}
function TeacherName({row}:{row:Row}){return <>{text(row.prefix)}{text(row.first_name)} {text(row.last_name)}</>;}
function Status({row}:{row:Row}){const status=text(row.handover_status)||"READY";const detail=status==="RECEIVED"?{label:"รับเครื่องแล้ว",icon:faCircleCheck}:status==="RETURNED"?{label:"คืนเครื่องแล้ว",icon:faRotateLeft}:{label:"พร้อมรับเครื่อง",icon:faClock};return <span className={`handover-status ${status.toLowerCase()}`}><FontAwesomeIcon icon={detail.icon}/>{detail.label}</span>;}
function EventBadge({action}:{action:string}){const detail=action==="HANDOVER"?{label:"รับเครื่อง",icon:faCircleCheck}:action==="RETURN"?{label:"คืนเครื่อง",icon:faRotateLeft}:{label:"ยกเลิก",icon:faBan};return <span className={`handover-event ${action.toLowerCase()}`}><FontAwesomeIcon icon={detail.icon}/>{detail.label}</span>;}

export function TeacherDeviceHandovers({canCancel}:{canCancel:boolean}){
  const [tab,setTab]=useState<Tab>("QUICK"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [rows,setRows]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[areas,setAreas]=useState<Area[]>([]);
  const [summary,setSummary]=useState<Summary>({total:0,ready:0,received:0,returned:0}),[total,setTotal]=useState(0),[historyTotal,setHistoryTotal]=useState(0);
  const [search,setSearch]=useState(""),[area,setArea]=useState(""),[status,setStatus]=useState(""),[historyAction,setHistoryAction]=useState(""),[page,setPage]=useState(1);
  const [teacherCode,setTeacherCode]=useState(""),[quickTeacher,setQuickTeacher]=useState<Row|null>(null),[quickNote,setQuickNote]=useState("");
  const [handoverTarget,setHandoverTarget]=useState<Row|null>(null),[cancelTarget,setCancelTarget]=useState<Row|null>(null);
  const codeInput=useRef<HTMLInputElement>(null);
  const pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),historyPages=Math.max(1,Math.ceil(historyTotal/PAGE_SIZE));
  const quickReady=Boolean(quickTeacher&&quickTeacher.eligible!==false&&text(quickTeacher.handover_record_status)!=="ACTIVE");
  const params=(mode:string)=>{const query=new URLSearchParams({mode,page:String(page)});if(search.trim())query.set("search",search.trim());if(area)query.set("area",area);if(mode==="list"&&status)query.set("status",status);if(mode==="history"&&historyAction)query.set("action",historyAction);return query;};

  async function loadList(silent=false){if(!silent)setLoading(true);try{const response=await fetch(`/api/admin/teacher-device-handovers?${params("list")}`,{cache:"no-store"}),body=await readJson<{rows?:Row[];summary?:Summary;areas?:Area[];total?:number;error?:string}>(response);if(!response.ok)throw new Error(body.error);setRows(body.rows??[]);setSummary(body.summary??{total:0,ready:0,received:0,returned:0});setAreas(body.areas??[]);setTotal(Number(body.total??0));}catch(error){toast.error(error instanceof Error?error.message:"โหลดสถานะรับเครื่องครูไม่สำเร็จ");}finally{if(!silent)setLoading(false);}}
  async function loadHistory(silent=false){if(!silent)setLoading(true);try{const response=await fetch(`/api/admin/teacher-device-handovers?${params("history")}`,{cache:"no-store"}),body=await readJson<{rows?:Row[];total?:number;error?:string}>(response);if(!response.ok)throw new Error(body.error);setHistory(body.rows??[]);setHistoryTotal(Number(body.total??0));}catch(error){toast.error(error instanceof Error?error.message:"โหลดประวัติไม่สำเร็จ");}finally{if(!silent)setLoading(false);}}
  useEffect(()=>{const timer=window.setTimeout(()=>{if(tab==="HISTORY")void loadHistory();else void loadList();},200);return()=>window.clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
  },[tab,page,search,area,status,historyAction]);
  const changeTab=(next:Tab)=>{setTab(next);setPage(1);};
  async function lookup(event:FormEvent){event.preventDefault();if(busy)return;if(quickReady&&quickTeacher){await handover(quickTeacher,quickNote,true);return;}const code=teacherCode.trim();if(!code){toast.warning("กรุณากรอกรหัสครู");return;}setBusy(true);setQuickTeacher(null);try{const query=new URLSearchParams({mode:"lookup",teacherCode:code}),response=await fetch(`/api/admin/teacher-device-handovers?${query}`,{cache:"no-store"}),body=await readJson<{teacher?:Row;error?:string}>(response);if(!response.ok)throw new Error(body.error);setQuickTeacher(body.teacher??null);}catch(error){toast.error(error instanceof Error?error.message:"ค้นหาครูไม่สำเร็จ");}finally{setBusy(false);}}
  async function handover(row:Row,note:string,quick=false){setBusy(true);try{const response=await fetch("/api/admin/teacher-device-handovers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"handover",teacherId:text(row.teacher_id),note})}),body=await readJson<{error?:string}>(response);if(!response.ok)throw new Error(body.error);toast.success("บันทึกครูรับเครื่องเรียบร้อยแล้ว");setHandoverTarget(null);if(quick){setQuickTeacher(null);setTeacherCode("");setQuickNote("");window.setTimeout(()=>codeInput.current?.focus(),0);}await Promise.all([loadList(true),loadHistory(true)]);}catch(error){toast.error(error instanceof Error?error.message:"บันทึกรับเครื่องไม่สำเร็จ");}finally{setBusy(false);}}
  async function cancel(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!cancelTarget)return;const reason=text(new FormData(event.currentTarget).get("reason"));setBusy(true);try{const response=await fetch("/api/admin/teacher-device-handovers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel",teacherId:text(cancelTarget.teacher_id),reason})}),body=await readJson<{error?:string}>(response);if(!response.ok)throw new Error(body.error);toast.success("ยกเลิกสถานะรับเครื่องแล้ว");setCancelTarget(null);await Promise.all([loadList(true),loadHistory(true)]);}catch(error){toast.error(error instanceof Error?error.message:"ยกเลิกสถานะไม่สำเร็จ");}finally{setBusy(false);}}
  const visibleHistory=useMemo(()=>history,[history]);

  return <>
    <div className="admin-topline document-checkin-topline"><div><span className="eyebrow">ระบบจัดการอุปกรณ์</span><h1 className="admin-page-title"><FontAwesomeIcon icon={faUserTie}/> สถานะการรับเครื่องครู</h1><p>ยืนยันการส่งมอบให้ครู แล้วเชื่อมรายการกับเมนูคืน iPad โดยอัตโนมัติ</p></div></div>
    <div className="handover-summary-grid teacher-handover-summary">
      <article><span><FontAwesomeIcon icon={faUsers}/></span><div><small>ลงทะเบียนรับ iPad</small><b>{summary.total.toLocaleString("th-TH")}</b><em>ราย</em></div></article>
      <article className="ready"><span><FontAwesomeIcon icon={faClock}/></span><div><small>พร้อมรับเครื่อง</small><b>{summary.ready.toLocaleString("th-TH")}</b><em>ราย</em></div></article>
      <article className="received"><span><FontAwesomeIcon icon={faCircleCheck}/></span><div><small>รับเครื่องแล้ว</small><b>{summary.received.toLocaleString("th-TH")}</b><em>ราย</em></div></article>
      <article className="returned"><span><FontAwesomeIcon icon={faRotateLeft}/></span><div><small>คืนเครื่องแล้ว</small><b>{summary.returned.toLocaleString("th-TH")}</b><em>ราย</em></div></article>
    </div>
    <section className="admin-panel document-checkin-panel">
      <div className="document-checkin-tabs" role="tablist" aria-label="รูปแบบสถานะรับเครื่องครู">
        <button type="button" role="tab" aria-selected={tab==="QUICK"} className={tab==="QUICK"?"active":""} onClick={()=>changeTab("QUICK")}><FontAwesomeIcon icon={faUserTie}/><span>เช็คด่วน</span></button>
        <button type="button" role="tab" aria-selected={tab==="LIST"} className={tab==="LIST"?"active":""} onClick={()=>changeTab("LIST")}><FontAwesomeIcon icon={faSchool}/><span>ตรวจตามกลุ่มสาระ</span></button>
        <button type="button" role="tab" aria-selected={tab==="HISTORY"} className={tab==="HISTORY"?"active":""} onClick={()=>changeTab("HISTORY")}><FontAwesomeIcon icon={faHistory}/><span>ประวัติ</span></button>
      </div>
      {tab==="QUICK"&&<div className="document-quick-layout"><div className="document-quick-entry"><span className="document-quick-icon"><FontAwesomeIcon icon={faMagnifyingGlass}/></span><div><h2>บันทึกครูรับเครื่องแบบรวดเร็ว</h2><p>{quickReady?"ตรวจสอบชื่อแล้วกด Enter อีกครั้งเพื่อยืนยัน":"กรอกรหัสครูแล้วกด Enter เพื่อค้นหา"}</p></div><form onSubmit={lookup}><label className="field"><span>รหัสครู</span><input ref={codeInput} autoFocus autoComplete="off" value={teacherCode} onChange={event=>{setTeacherCode(event.target.value);setQuickTeacher(null);}} placeholder="กรอกรหัสครู"/></label><button className="button primary" disabled={busy}><FontAwesomeIcon icon={busy?faSpinner:quickReady?faCheck:faMagnifyingGlass} spin={busy}/>{busy?"กำลังดำเนินการ...":quickReady?"ยืนยันรับเครื่อง":"ตรวจสอบ"}</button></form>{quickReady&&<label className="field"><span>หมายเหตุ</span><input value={quickNote} onChange={event=>setQuickNote(event.target.value)} placeholder="ไม่บังคับ"/></label>}</div><div className={`document-quick-result${quickTeacher?" has-result":""}`}>{!quickTeacher?<div className="document-quick-empty"><FontAwesomeIcon icon={faTabletScreenButton}/><b>รอกรอกรหัสครู</b><span>ระบบจะตรวจการลงทะเบียนและสถานะรับเครื่องก่อนบันทึก</span></div>:<><header><div><small>ข้อมูลครู</small><h3><TeacherName row={quickTeacher}/></h3><p>{text(quickTeacher.learning_area)||"ไม่ระบุกลุ่มสาระ"} · รหัส {text(quickTeacher.teacher_code)}</p></div><Status row={quickTeacher}/></header><div className="handover-device-line"><span>Serial Number</span><b>{text(quickTeacher.serial_number)||"ไม่ระบุ (ไม่บังคับ)"}</b></div>{quickTeacher.eligible===false?<div className="document-ineligible"><FontAwesomeIcon icon={faBan}/><span>{text(quickTeacher.eligibilityReason)}</span></div>:<><div className="document-enter-hint"><kbd>Enter</kbd><span>กดอีกครั้งเพื่อยืนยันรับเครื่อง</span></div><button type="button" className="button primary document-receive-button" disabled={busy} onClick={()=>void handover(quickTeacher,quickNote,true)}><FontAwesomeIcon icon={busy?faSpinner:faCheck} spin={busy}/> บันทึกรับเครื่องแล้ว</button></>}</>}</div></div>}
      {tab==="LIST"&&<><ListHeading title="สถานะรับเครื่องครูตามกลุ่มสาระ" subtitle="Serial Number เป็นข้อมูลเสริม สามารถบันทึกรับเครื่องได้แม้ยังไม่ได้กรอก"/><Filters search={search} setSearch={setSearch} area={area} setArea={setArea} areas={areas} status={status} setStatus={setStatus}/>{loading?<Loading/>:<div className="admin-table-wrap"><table className="admin-table handover-table"><thead><tr><th>รหัส</th><th>ชื่อ-นามสกุล</th><th>กลุ่มสาระ</th><th>Serial Number</th><th>สถานะรับเครื่อง</th><th>วันรับ / ผู้ดำเนินการ</th><th>จัดการ</th></tr></thead><tbody>{rows.map(row=>{const state=text(row.handover_status);return <tr key={text(row.teacher_id)}><td><b>{text(row.teacher_code)}</b></td><td><TeacherName row={row}/></td><td>{text(row.learning_area)||"—"}</td><td><code>{text(row.serial_number)||"ไม่ระบุ"}</code></td><td><Status row={row}/></td><td>{state==="RECEIVED"?<><b className="document-receiver">{text(row.handed_over_by_name)||"ผู้ดูแลระบบ"}</b><small className="document-date">{formatDateTime(row.handed_over_at)}</small></>:state==="RETURNED"?<><b className="document-receiver">คืนแล้ว</b><small className="document-date">{formatDateTime(row.returned_at)}</small></>:"—"}</td><td><div className="table-actions">{state==="RECEIVED"?canCancel&&<button type="button" className="icon-button danger-icon-button" title="ยกเลิกสถานะรับเครื่อง" onClick={()=>setCancelTarget(row)}><FontAwesomeIcon icon={faXmark}/></button>:<button type="button" className="button handover-row-button" onClick={()=>setHandoverTarget(row)}><FontAwesomeIcon icon={faCheck}/> รับเครื่อง</button>}</div></td></tr>;})}</tbody></table>{!rows.length&&<div className="empty-state small">ไม่พบรายการตามตัวกรอง</div>}<Pagination page={page} pages={pages} total={total} setPage={setPage}/></div>}</>}
      {tab==="HISTORY"&&<><ListHeading title="ประวัติสถานะรับเครื่องครู" subtitle="แสดงการรับเครื่อง การคืน และการยกเลิก พร้อมผู้ดำเนินการ"/><div className="handover-filters"><label className="search-box admin-search"><FontAwesomeIcon icon={faMagnifyingGlass}/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="ค้นหารหัสหรือชื่อครู..."/></label><select className="admin-input" value={area} onChange={event=>{setArea(event.target.value);setPage(1);}}><option value="">ทุกกลุ่มสาระ</option>{areas.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="admin-input" value={historyAction} onChange={event=>{setHistoryAction(event.target.value);setPage(1);}}><option value="">ทุกการดำเนินการ</option><option value="HANDOVER">รับเครื่อง</option><option value="RETURN">คืนเครื่อง</option><option value="CANCEL">ยกเลิกสถานะ</option></select></div>{loading?<Loading/>:<div className="admin-table-wrap"><table className="admin-table handover-history-table"><thead><tr><th>วันเวลา</th><th>ครู</th><th>กลุ่มสาระ</th><th>รายการ</th><th>Serial Number</th><th>ผู้ดำเนินการ</th><th>หมายเหตุ</th></tr></thead><tbody>{visibleHistory.map(row=><tr key={text(row.id)}><td>{formatDateTime(row.created_at)}</td><td><b>{text(row.teacher_code)}</b><span><TeacherName row={row}/></span></td><td>{text(row.learning_area)||"—"}</td><td><EventBadge action={text(row.action)}/></td><td><code>{text(row.serial_number)||"ไม่ระบุ"}</code></td><td>{text(row.processed_by_name)||"ผู้ดูแลระบบ"}</td><td>{text(row.note)||"—"}</td></tr>)}</tbody></table>{!visibleHistory.length&&<div className="empty-state small">ยังไม่มีประวัติตามตัวกรอง</div>}<Pagination page={page} pages={historyPages} total={historyTotal} setPage={setPage}/></div>}</>}
    </section>
    {handoverTarget&&<TeacherHandoverModal row={handoverTarget} busy={busy} close={()=>setHandoverTarget(null)} submit={handover}/>} 
    {cancelTarget&&<div className="modal-backdrop"><section className="modal document-cancel-modal"><div className="modal-icon danger-icon"><FontAwesomeIcon icon={faBan}/></div><h2>ยกเลิกสถานะรับเครื่องครู</h2><p><TeacherName row={cancelTarget}/></p><form onSubmit={cancel}><label className="field"><span>เหตุผล <b>*</b></span><textarea name="reason" minLength={3} maxLength={500} required/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setCancelTarget(null)}>ไม่ยกเลิก</button><button className="button danger-solid" disabled={busy}><FontAwesomeIcon icon={busy?faSpinner:faBan} spin={busy}/> ยืนยันยกเลิก</button></div></form></section></div>}
  </>;
}

function ListHeading({title,subtitle}:{title:string;subtitle:string}){return <div className="document-list-heading"><div><h2><FontAwesomeIcon icon={faSchool}/> {title}</h2><p>{subtitle}</p></div></div>;}
function Loading(){return <div className="loading-row"><FontAwesomeIcon icon={faSpinner} spin/> กำลังโหลดข้อมูล...</div>;}
function Filters({search,setSearch,area,setArea,areas,status,setStatus}:{search:string;setSearch:(v:string)=>void;area:string;setArea:(v:string)=>void;areas:Area[];status:string;setStatus:(v:string)=>void}){return <div className="handover-filters"><label className="search-box admin-search"><FontAwesomeIcon icon={faMagnifyingGlass}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="ค้นหารหัสหรือชื่อครู..."/></label><select className="admin-input" value={area} onChange={event=>setArea(event.target.value)}><option value="">ทุกกลุ่มสาระ</option>{areas.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="admin-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="">ทุกสถานะ</option><option value="READY">พร้อมรับเครื่อง</option><option value="RECEIVED">รับเครื่องแล้ว</option><option value="RETURNED">คืนเครื่องแล้ว</option></select></div>;}
function TeacherHandoverModal({row,busy,close,submit}:{row:Row;busy:boolean;close:()=>void;submit:(row:Row,note:string)=>Promise<void>}){function save(event:FormEvent<HTMLFormElement>){event.preventDefault();void submit(row,text(new FormData(event.currentTarget).get("note")));}return <div className="modal-backdrop"><section className="modal return-device-modal"><header className="return-device-modal-header"><span><FontAwesomeIcon icon={faTabletScreenButton}/></span><div><small>ยืนยันการส่งมอบอุปกรณ์</small><h2>บันทึกครูรับเครื่อง</h2></div><button className="icon-button" type="button" disabled={busy} onClick={close}><FontAwesomeIcon icon={faXmark}/></button></header><div className="return-holder-card"><span className="holder-type teacher"><FontAwesomeIcon icon={faUserTie}/>ครูและบุคลากร</span><div><b><TeacherName row={row}/></b><span>{text(row.learning_area)||"ไม่ระบุกลุ่มสาระ"} · รหัส {text(row.teacher_code)}</span></div><code>{text(row.serial_number)||"ไม่ระบุ Serial (ไม่บังคับ)"}</code></div><form className="return-device-form" onSubmit={save}><label className="field full"><span>หมายเหตุ</span><textarea name="note" rows={3} maxLength={500} placeholder="ไม่บังคับ"/></label><div className="modal-actions full"><button type="button" className="button secondary" disabled={busy} onClick={close}>ยกเลิก</button><button className="button primary" disabled={busy}><FontAwesomeIcon icon={busy?faSpinner:faCheck} spin={busy}/>{busy?"กำลังบันทึก...":"ยืนยันรับเครื่อง"}</button></div></form></section></div>;}
function Pagination({page,pages,total,setPage}:{page:number;pages:number;total:number;setPage:(v:number)=>void}){if(total<=PAGE_SIZE)return null;return <nav className="table-pagination"><span>ทั้งหมด {total.toLocaleString("th-TH")} รายการ</span><div><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)}><FontAwesomeIcon icon={faChevronLeft}/></button><b>หน้า {page.toLocaleString("th-TH")} / {pages.toLocaleString("th-TH")}</b><button type="button" disabled={page>=pages} onClick={()=>setPage(page+1)}><FontAwesomeIcon icon={faChevronRight}/></button></div></nav>;}
